# Generated by Django 2.2.1 on 2019-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Доступный Цвет',
                'verbose_name_plural': 'Доступные Цвета',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEN', models.CharField(default='', max_length=120, verbose_name='Название на английском')),
                ('nameRU', models.CharField(max_length=120, verbose_name='Название на русском')),
                ('nameUZ', models.CharField(default='', max_length=120, verbose_name='Название на узбекском')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='EthernetTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Тип интернета',
                'verbose_name_plural': 'Тип интернета',
            },
        ),
        migrations.CreateModel(
            name='UsbTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Тип USB',
                'verbose_name_plural': 'Типы USB',
            },
        ),
    ]
