# Generated by Django 2.2.1 on 2019-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesForProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=120, verbose_name='Название фото')),
                ('image1', models.ImageField(default=None, upload_to='', verbose_name='Фото-1')),
                ('image2', models.ImageField(default=None, upload_to='', verbose_name='Фото-2')),
                ('image3', models.ImageField(default=None, upload_to='', verbose_name='Фото-3')),
            ],
        ),
    ]
