# Generated by Django 2.2.3 on 2019-07-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190709_0904'),
        ('infodb', '0002_imagesforproductsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorTypeModel',
        ),
        migrations.AlterModelOptions(
            name='imagesforproductsmodel',
            options={'verbose_name': 'Фото для продукта', 'verbose_name_plural': 'Фото для Продуктов'},
        ),
    ]
