# Generated by Django 2.2.3 on 2019-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodb', '0003_auto_20190709_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Процессор')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Материал')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Операционная система')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfChargingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Тип разъема для зарядки')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfDisplayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Тип экрана')),
            ],
        ),
    ]
