# Generated by Django 2.2.3 on 2019-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodb', '0004_cpumodel_materialmodel_operatingsystemmodel_typeofchargingmodel_typeofdisplaymodel'),
        ('products', '0004_auto_20190710_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EthernetTypeModel',
        ),
        migrations.DeleteModel(
            name='ImagesForProductsModel',
        ),
        migrations.DeleteModel(
            name='UsbTypeModel',
        ),
        migrations.AlterModelOptions(
            name='countrymodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='nameEN',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='nameRU',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='nameUZ',
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='name',
            field=models.CharField(default=None, max_length=120, verbose_name='Страна'),
        ),
    ]
