# Generated by Django 2.2.1 on 2019-05-27 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infodb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('idx', models.IntegerField(default=-1, verbose_name='ID категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SmartPhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('bluetooth', models.CharField(max_length=120, verbose_name='Версия блютуза')),
                ('wifi', models.CharField(max_length=120, verbose_name='Версия вай-фая')),
                ('nfc', models.BooleanField(default=False, verbose_name='NFC')),
                ('display', models.CharField(max_length=120, verbose_name='Тип дисплея')),
                ('diagonal', models.FloatField(verbose_name='Диагональ')),
                ('resolution', models.CharField(max_length=120, verbose_name='Разрешение(300x200)')),
                ('sensor', models.BooleanField(default=True, verbose_name='Сенсор')),
                ('pixil', models.CharField(max_length=120, verbose_name='Камеры в пиксилях (12 МП + 10 МП)')),
                ('diaphragm', models.CharField(max_length=120, verbose_name='Диафрагмы ( F1.5/F2.4 + F2.2 )')),
                ('zoom', models.BooleanField(default=False, verbose_name='Зум камеры')),
                ('focus', models.BooleanField(default=False, verbose_name='Автофокус')),
                ('cameraresol', models.CharField(max_length=120, verbose_name='Разрешение записи ( 200x300 + 400x500 )')),
                ('cpu', models.CharField(max_length=120, verbose_name='Процессор')),
                ('cores', models.IntegerField(verbose_name='Количество ядер')),
                ('frequency', models.CharField(max_length=120, verbose_name='Частота (2.4)')),
                ('ram', models.IntegerField(verbose_name='Озу')),
                ('memory', models.IntegerField(verbose_name='Память')),
                ('externalMemory', models.IntegerField(verbose_name='Внешняя память до')),
                ('sim', models.CharField(max_length=30, verbose_name='Тип симкарты (Nano,Big)')),
                ('simCount', models.IntegerField(verbose_name='Кол-во Сим-Карт')),
                ('system', models.CharField(max_length=120, verbose_name='Система')),
                ('mass', models.FloatField(max_length=120, verbose_name='Вес(г)')),
                ('capacity', models.IntegerField(verbose_name='Емкость акамулятора')),
                ('garant', models.CharField(max_length=120, verbose_name='Гарантия')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.CategoriesModel', verbose_name='Категория')),
                ('color', models.ManyToManyField(to='infodb.ColorTypeModel', verbose_name='Цвет')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='infodb.CountryModel', verbose_name='Страна')),
                ('ethernet', models.ManyToManyField(to='infodb.EthernetTypeModel', verbose_name='Тип интернета')),
                ('usb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infodb.UsbTypeModel', verbose_name='Тип USB')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Смартфоны и Планшеты',
                'verbose_name_plural': 'Смартфоны и Планшеты',
            },
        ),
    ]
