# Generated by Django 2.2.3 on 2019-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_smartphonemodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphonemodel',
            name='color',
        ),
        migrations.AddField(
            model_name='smartphonemodel',
            name='color',
            field=models.CharField(default=None, max_length=120, verbose_name='Цвета'),
            preserve_default=False,
        ),
    ]
